DKSail/Controllers/DKMemberController.cs
/*
 * Program: DKSail
 * 
 * Name: Dongha Kang
 * Student Number: 8004178
 *        
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DKSail.Models;
using Microsoft.AspNetCore.Http;
using System.Text.RegularExpressions;

namespace DKSail.Controllers
{
    public class DKMemberController : Controller
    {
        private readonly SailContext _context;

        public DKMemberController(SailContext context)
        {
            _context = context;
        }

        // GET: DKMember
        public async Task<IActionResult> Index()
        {
            var sailContext = _context.Member.Include(m => m.ProvinceCodeNavigation);
            return View(await sailContext.OrderBy(x => x.FullName).ToListAsync());
        }

        // GET: DKMember/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .Include(m => m.ProvinceCodeNavigation)
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            var memberName = member.FullName;
            ViewBag.memberName = memberName;

            return View(member);
        }

        // GET: DKMember/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DKMember/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberId,FirstName,LastName,SpouseFirstName,SpouseLastName,Street,City,ProvinceCode,PostalCode,HomePhone,Email,YearJoined,Comment,TaskExempt,UseCanadaPost")] Member member)
        {
            // since MemberId is not an autonumber
            var lastMember = _context.Member.LastOrDefault().MemberId;
            member.MemberId = lastMember + 1;



            if (ModelState.IsValid)
            {
                _context.Add(member);
                await _context.SaveChangesAsync();
                TempData["Message"] = "Created Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: DKMember/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }

            var memberName = member.FullName;
            ViewBag.memberName = memberName;

            ViewData["ProvinceCode"] = new SelectList(_context.Province.OrderBy(x => x.Name), "ProvinceCode", "Name", member.ProvinceCode);
            return View(member);
        }

        // POST: DKMember/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberId,FullName,FirstName,LastName,SpouseFirstName,SpouseLastName,Street,City,ProvinceCode,PostalCode,HomePhone,Email,YearJoined,Comment,TaskExempt,UseCanadaPost")] Member member)
        {
            HttpContext.Session.SetString("currentMember", member.MemberId.ToString());

            if (id != member.MemberId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                    TempData["Message"] = "Updated Successfully";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.MemberId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province.OrderBy(x => x.Name), "ProvinceCode", "Name", member.ProvinceCode);
            return View(member);
        }

        // GET: DKMember/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .Include(m => m.ProvinceCodeNavigation)
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            var memberName = member.FullName;
            ViewBag.memberName = memberName;

            return View(member);
        }

        // POST: DKMember/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var member = await _context.Member.FindAsync(id);
                _context.Member.Remove(member);
                await _context.SaveChangesAsync();
                TempData["Message"] = "Deleted Successfully";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                if (ex.GetBaseException() != null)
                {
                    TempData["Message"] = ex.GetBaseException().Message;
                }

                //if(ex.InnerException != null)
                //{
                //    TempData["Message"] = ex.InnerException.ToString();
                //}
                //else
                //{
                //    TempData["Message"] = ex.ToString();
                //}                   

                return RedirectToAction(nameof(Index));
            }
        }

        private bool MemberExists(int id)
        {
            return _context.Member.Any(e => e.MemberId == id);
        }



        // Remote Validation

        private bool IsProvinceCodeValid(string provinceCode)
        {
            if (!string.IsNullOrWhiteSpace(provinceCode))
            {
                provinceCode = provinceCode.Trim().ToUpper();

                var provinceCodeOnRecord = _context.Province.Where(x => x.ProvinceCode == provinceCode).FirstOrDefault();


                if (provinceCodeOnRecord == null)
                {
                    return false;
                }
                else
                {
                    var country = _context.Province.Where(x => x.ProvinceCode == provinceCodeOnRecord.ProvinceCode).FirstOrDefault().CountryCode;
                    HttpContext.Session.SetString("countryCode", country);
                }
            }

            return true;
        }

        public JsonResult ValidateProvinceCode(string provinceCode, string postalCode)
        {
            if (!IsProvinceCodeValid(provinceCode))                
            {
                return Json("Province Code is not on file");
            }

            if (!IsPostalCodeValid(postalCode, provinceCode) && !string.IsNullOrEmpty(postalCode))
            {
                return Json("Province Code is not valid for this Postal Code");
            }
            return Json(true);

        }

        private bool IsPostalCodeValid(string postalCode, string provinceCode)
        {
            if (postalCode != null && postalCode != "")
            {
                if (!IsProvinceCodeValid(provinceCode))
                {
                    return false;
                }

                var country = HttpContext.Session.GetString("countryCode");

                if (country != null)
                {
                    var postalPattern = _context.Country.Where(x => x.CountryCode == country).FirstOrDefault().PostalPattern;
                    if (postalPattern != null)
                    {
                        if (country == "US")
                        {
                            postalCode = DKClassLibrary.DKValidations.DKExtractDigits(postalCode);
                        }
                        if (!Regex.IsMatch(postalCode.Trim(), postalPattern, RegexOptions.IgnoreCase))
                        {
                            return false;
                        }
                    }
                }
            }
            return true;
        }

        public JsonResult ValidatePostalCode(string postalCode, string provinceCode)
        {
            if (!IsPostalCodeValid(postalCode, provinceCode))
            {
                return Json("Postal Code is not valid");
            }
            return Json(true);
        }
    }
}

DKSail/Controllers/DKTasksController.cs
/*
 * Program: DKSail
 * 
 * Name: Dongha Kang
 * Student Number: 8004178
 *        
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DKSail.Models;

namespace DKSail.Controllers
{
    public class DKTasksController : Controller
    {
        private readonly SailContext _context;

        public DKTasksController(SailContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Shows a list of Tasks
        /// </summary>
        /// <returns>a view that contains a list of Tasks</returns>
        // GET: DKTasks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tasks.ToListAsync());
        }
        /// <summary>
        /// Shows details of a Task when there is an id
        /// </summary>
        /// <param name="id">Task model id</param>
        /// <returns>a view that contails details of the Task with the corresponding id</returns>
        // GET: DKTasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks
                .FirstOrDefaultAsync(m => m.TaskId == id);
            if (tasks == null)
            {
                return NotFound();
            }

            return View(tasks);
        }
        /// <summary>
        /// Shows a creat page with blank input fields
        /// </summary>
        /// <returns>a view that contains input fields for Task creation</returns>
        // GET: DKTasks/Create
        public IActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// Saves newly created Task to the list
        /// </summary>
        /// <param name="tasks">a Task object created from user input</param>
        /// <returns>a view that contains the list of Tasks including the newly added</returns>
        // POST: DKTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TaskId,Name,Description")] Tasks tasks)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tasks);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tasks);
        }
        /// <summary>
        /// Shows a edit page with input fields filled with corresponding data
        /// </summary>
        /// <param name="id">Task model id</param>
        /// <returns>a view that contains input fields for Task edit</returns>
        // GET: DKTasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks.FindAsync(id);
            if (tasks == null)
            {
                return NotFound();
            }
            return View(tasks);
        }
        /// <summary>
        /// Saves newly edited Task to the list
        /// </summary>
        /// <param name="id">Task model id</param>
        /// <param name="tasks">a Task object corresponding to id parameter</param>
        /// <returns>a view that contains the list of Tasks including the newly edited</returns>
        // POST: DKTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TaskId,Name,Description")] Tasks tasks)
        {
            if (id != tasks.TaskId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tasks);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TasksExists(tasks.TaskId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tasks);
        }
        /// <summary>
        /// Shows a delete page
        /// </summary>
        /// <param name="id">Task model id</param>
        /// <returns>a view that contains the Task details with the corresponding id</returns>
        // GET: DKTasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks
                .FirstOrDefaultAsync(m => m.TaskId == id);
            if (tasks == null)
            {
                return NotFound();
            }

            return View(tasks);
        }
        /// <summary>
        /// Saves the list excluding the newly deleted item from it
        /// </summary>
        /// <param name="id">Task model id</param>
        /// <returns>a confirmation page</returns>
        // POST: DKTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tasks = await _context.Tasks.FindAsync(id);
            _context.Tasks.Remove(tasks);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        /// <summary>
        /// a helper method to identify whether a certain Task with this id exists
        /// </summary>
        /// <param name="id">Task model id</param>
        /// <returns>a boolean value of whether the Task exists</returns>
        private bool TasksExists(int id)
        {
            return _context.Tasks.Any(e => e.TaskId == id);
        }
    }
}

DKSail/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Crystal Lake Sailing</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css"  asp-append-version="true"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="min-height: 125px;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/logo.jpg" height="100" /></a>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="line-height: 100px;">Crystal Lake Sailing</a>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index" style="line-height: 100px;">Home</a></li>
                    <li><a asp-area="" asp-controller="DKBoatType" asp-action="Index" style="line-height: 100px;">Boat Types</a></li>
                    <li><a asp-area="" asp-controller="DKMember" asp-action="Index" style="line-height: 100px;">Member</a></li>
                    <li><a asp-area="" asp-controller="DKParking" asp-action="Index" style="line-height: 100px;">Parking</a></li>
                    <li><a asp-area="" asp-controller="DKMembershipType" asp-action="Index" style="line-height: 100px;">Membership Types</a></li>
                    <li><a asp-area="" asp-controller="DKTasks" asp-action="Index" style="line-height: 100px;">Tasks</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        <div style="color:red;"><strong>@TempData["Message"]</strong></div>
        @RenderBody()
        <hr />
        <footer>
            <div>
                <div style="float:left;">
                    &copy; <a href="mailto:dkang4178@conestogac.on.ca">2018 - Dongha Kang - Sec4</a>
                </div>

                <div style="float:right">
                    <a asp-area="" asp-controller="Home" asp-action="About">About</a>
                    <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                </div>                
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>