DKSail/Controllers/DKBoatController.cs
/*
 * Program: DKSail
 * 
 * Name: Dongha Kang
 * Student Number: 8004178
 *        
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DKSail.Models;
using Microsoft.AspNetCore.Http;

namespace DKSail.Controllers
{
    public class DKBoatController : Controller
    {
        private readonly SailContext _context;

        public DKBoatController(SailContext context)
        {
            _context = context;
        }

        // GET: DKBoat
        public async Task<IActionResult> Index(int? memberId, string memberName)
        {
            var memberIdContext = _context.Member.Where(x => x.MemberId == memberId).FirstOrDefault();
            var memberNameContext = _context.Member.Where(x => x.FullName == memberName).FirstOrDefault();

            if (memberId == null && memberName == null)
            {
                if (HttpContext.Session.GetString("memberId") == null && HttpContext.Session.GetString("memberName") == null)
                {
                    TempData["Message"] = "Please select a member";
                    return RedirectToAction("Index", "DKMember");
                }
                else if (HttpContext.Session.GetString("memberId") != null && HttpContext.Session.GetString("memberName") == null)
                {
                    memberId = int.Parse(HttpContext.Session.GetString("memberId"));
                    memberName = _context.Member.Where(x => x.MemberId == memberId).FirstOrDefault().FullName;
                    HttpContext.Session.SetString("memberName", memberName);
                }
                else if (HttpContext.Session.GetString("memberId") == null && HttpContext.Session.GetString("memberName") != null)
                {
                    memberName = HttpContext.Session.GetString("memberName");
                    memberId = _context.Member.Where(x => x.FullName == memberName).FirstOrDefault().MemberId;
                    HttpContext.Session.SetString("memberId", memberId.ToString());
                }
                else
                {
                    memberId = int.Parse(HttpContext.Session.GetString("memberId"));
                    memberName = HttpContext.Session.GetString("memberName");
                }
            }
            else if (memberId == null && memberName != null)
            {
                if (memberNameContext == null)
                {
                    TempData["Message"] = "MemberName does not exist";
                    return RedirectToAction("Index", "DKMember");
                }
                memberId = _context.Member.Where(x => x.FullName == memberName).FirstOrDefault().MemberId;
                HttpContext.Session.SetString("memberId", memberId.ToString());
                HttpContext.Session.SetString("memberName", memberName);
            }
            else if (memberId != null && memberName == null)
            {
                if (memberIdContext == null)
                {
                    TempData["Message"] = "MemberId does not exist";
                    return RedirectToAction("Index", "DKMember");
                }
                memberName = _context.Member.Where(x => x.MemberId == memberId).FirstOrDefault().FullName;
                HttpContext.Session.SetString("memberId", memberId.ToString());
                HttpContext.Session.SetString("memberName", memberName);
            }
            else
            {
                if (memberIdContext == null)
                {
                    TempData["Message"] = "MemberId does not exist";
                    return RedirectToAction("Index", "DKMember");
                }

                var nameToFind = memberIdContext.FullName;
                if (memberName != nameToFind)
                {
                    TempData["Message"] = "MemberId does not match with MemberName";
                    return RedirectToAction("Index", "DKMember");
                }

                HttpContext.Session.SetString("memberId", memberId.ToString());
                HttpContext.Session.SetString("memberName", memberName);
            }

            ViewBag.memberId = memberId;
            ViewBag.memberName = memberName;

            var sailContext = await _context.Boat.Include(b => b.BoatType).Include(b => b.Member).Include(b => b.ParkingCodeNavigation).Where(x => x.MemberId == memberId).OrderBy(x => x.BoatClass).ToListAsync();
            return View(sailContext);
        }

        // GET: DKBoat/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.memberId = HttpContext.Session.GetString("memberId");
            ViewBag.memberName = HttpContext.Session.GetString("memberName");

            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boat
                .Include(b => b.BoatType)
                .Include(b => b.Member)
                .Include(b => b.ParkingCodeNavigation)
                .FirstOrDefaultAsync(m => m.BoatId == id);
            if (boat == null)
            {
                return NotFound();
            }

            return View(boat);
        }

        // GET: DKBoat/Create
        public IActionResult Create()
        {
            ViewBag.memberId = HttpContext.Session.GetString("memberId");
            ViewBag.memberName = HttpContext.Session.GetString("memberName");

            ViewData["BoatTypeId"] = new SelectList(_context.BoatType.OrderBy(x => x.Name), "BoatTypeId", "Name");
            ViewData["MemberId"] = new SelectList(_context.Member, "MemberId", "FirstName");
            ViewData["ParkingCode"] = new SelectList(_context.Parking.Where(x => x.ActualBoatId == null), "ParkingCode", "ParkingCode");
            return View();
        }

        // POST: DKBoat/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BoatId,MemberId,BoatClass,HullColour,SailNumber,HullLength,BoatTypeId,ParkingCode")] Boat boat)
        {
            boat.MemberId = int.Parse(HttpContext.Session.GetString("memberId"));

            if (ModelState.IsValid)
            {
                //to update actualBoatId in parking table
                var newParking = _context.Parking.Where(x => x.ParkingCode == boat.ParkingCode).FirstOrDefault();
                newParking.ActualBoatId = boat.BoatId.ToString();
                ////////////////////////////////////////

                _context.Add(boat);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["BoatTypeId"] = new SelectList(_context.BoatType.OrderBy(x => x.Name), "BoatTypeId", "Name", boat.BoatTypeId);
            ViewData["MemberId"] = new SelectList(_context.Member, "MemberId", "FirstName", boat.MemberId);
            ViewData["ParkingCode"] = new SelectList(_context.Parking.Where(x => x.ActualBoatId == null), "ParkingCode", "ParkingCode", boat.ParkingCode);
            return View(boat);
        }

        // GET: DKBoat/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.memberId = HttpContext.Session.GetString("memberId");
            ViewBag.memberName = HttpContext.Session.GetString("memberName");
            
            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boat.FindAsync(id);

            if (boat == null)
            {
                return NotFound();
            }
            
            //to update actualBoatId in parking table
            var oldParkingCode = _context.Boat.Where(x => x.BoatId == id).FirstOrDefault().ParkingCode;
            HttpContext.Session.SetString("oldParkingCode", oldParkingCode);
            ////////////////////////////////////////

            ViewData["BoatTypeId"] = new SelectList(_context.BoatType.OrderBy(x => x.Name), "BoatTypeId", "Name", boat.BoatTypeId);
            ViewData["MemberId"] = new SelectList(_context.Member, "MemberId", "FirstName", boat.MemberId);

            if (boat.ParkingCode == "" || boat.ParkingCode == null)
            {
                ViewData["ParkingCode"] = new SelectList(_context.Parking.Where(x => x.ActualBoatId == null), "ParkingCode", "ParkingCode", boat.ParkingCode); 
            }
            else
            {
                ViewData["ParkingCode"] = new SelectList(_context.Parking.Where(x => x.BoatTypeId == boat.BoatTypeId && x.ActualBoatId == null), "ParkingCode", "ParkingCode", boat.ParkingCode);
            }
            return View(boat);
        }

        // POST: DKBoat/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BoatId,MemberId,BoatClass,HullColour,SailNumber,HullLength,BoatTypeId,ParkingCode")] Boat boat)
        {
            if (id != boat.BoatId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //to update actualBoatId in parking table
                    var oldParkingCode = HttpContext.Session.GetString("oldParkingCode");
                    var oldParking = _context.Parking.Where(x => x.ParkingCode == oldParkingCode).FirstOrDefault();
                    oldParking.ActualBoatId = null;

DKSail/Views/DKMember/Create.cshtml
@model DKSail.Models.Member

@{
    ViewData["Title"] = "Create New Member";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpouseFirstName" class="control-label"></label>
                <input asp-for="SpouseFirstName" class="form-control" />
                <span asp-validation-for="SpouseFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpouseLastName" class="control-label"></label>
                <input asp-for="SpouseLastName" class="form-control" />
                <span asp-validation-for="SpouseLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProvinceCode" class="control-label"></label>
                <input asp-for="ProvinceCode" class="form-control" />
                <span asp-validation-for="ProvinceCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomePhone" class="control-label"></label>
                <input asp-for="HomePhone" class="form-control" />
                <span asp-validation-for="HomePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearJoined" class="control-label"></label>
                <input asp-for="YearJoined" class="form-control" />
                <span asp-validation-for="YearJoined" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="TaskExempt" /> @Html.DisplayNameFor(model => model.TaskExempt)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="UseCanadaPost" /> @Html.DisplayNameFor(model => model.UseCanadaPost)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DKSail/Views/DKMember/Delete.cshtml
@model DKSail.Models.Member

@{
    ViewData["Title"] = "Delete " + ViewBag.memberName;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SpouseFirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SpouseFirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SpouseLastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SpouseLastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.YearJoined)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.YearJoined)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaskExempt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaskExempt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UseCanadaPost)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UseCanadaPost)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProvinceCodeNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProvinceCodeNavigation.ProvinceCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MemberId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DKSail/Views/DKMember/Details.cshtml
@model DKSail.Models.Member

@{
    ViewData["Title"] = "Details for " + ViewBag.memberName;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MemberId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MemberId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SpouseFirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SpouseFirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SpouseLastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SpouseLastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.YearJoined)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.YearJoined)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaskExempt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaskExempt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UseCanadaPost)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UseCanadaPost)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProvinceCodeNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProvinceCodeNavigation.ProvinceCode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MemberId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DKSail/Views/DKMember/Edit.cshtml
@model DKSail.Models.Member

@{
    ViewData["Title"] = "Edit " + ViewBag.memberName;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MemberId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpouseFirstName" class="control-label"></label>
                <input asp-for="SpouseFirstName" class="form-control" />
                <span asp-validation-for="SpouseFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpouseLastName" class="control-label"></label>
                <input asp-for="SpouseLastName" class="form-control" />
                <span asp-validation-for="SpouseLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProvinceCode" class="control-label"></label>
                <select asp-for="ProvinceCode" class="form-control" asp-items="ViewBag.ProvinceCode"></select>
                <span asp-validation-for="ProvinceCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomePhone" class="control-label"></label>
                <input asp-for="HomePhone" class="form-control" />
                <span asp-validation-for="HomePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearJoined" class="control-label"></label>
                <input asp-for="YearJoined" class="form-control" />
                <span asp-validation-for="YearJoined" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="TaskExempt" /> @Html.DisplayNameFor(model => model.TaskExempt)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="UseCanadaPost" /> @Html.DisplayNameFor(model => model.UseCanadaPost)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DKSail/Views/DKMember/Index.cshtml
@model IEnumerable<DKSail.Models.Member>

@{
    ViewData["Title"] = "Member List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th hidden>
                @Html.DisplayNameFor(model => model.MemberId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HomePhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearJoined)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskExempt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UseCanadaPost)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td hidden>
                @Html.DisplayFor(modelItem => item.MemberId)
            </td>
            <td>
                <a asp-action="Index" asp-controller="DKMembership" asp-route-memberID="@item.MemberId">@Html.DisplayFor(modelItem => item.FullName)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HomePhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearJoined)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TaskExempt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UseCanadaPost)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MemberId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MemberId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MemberId">Delete</a> |
                <a asp-action="Index" asp-controller="DKBoat" asp-route-memberId="@item.MemberId" asp-route-memberName="@item.FullName">Show Boats</a>
            </td>
        </tr>
}
    </tbody>
</table>